#!/usr/bin/env bash

DOTFILES=$( cd $(dirname "${BASH_SOURCE[0]}" ) && pwd)

# kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# Zsh
rm $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

# Zsh Custom Plugins
rm -rf $HOME/.oh-my-zsh/custom/plugins
ln -s $DOTFILES/zsh/plugins $HOME/.oh-my-zsh/custom/plugins

# tmux
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf


mkdir -p $HOME/.local/bin


rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

# nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

